#!/bin/sh

ali_docker() {
	#
	# run a container with the source locally on the Mac
	# and the build/install in a managed docker container
	#
	context=${1:="o2-dev"}

	what=${2:="O2"}

	shift 2

	if ! test -d $HOME/alice/$context/$what; then
		echo "Directory $HOME/alice/$context/$what does not exists !"
		echo "The directories I know of in :"
		ls -d $HOME/alice/*
		return
	fi

	if ! dexist "$context"; then
		echo "--- Starting a new container"
		echo "----- trailing arguments passed as is : $@"
		detach=${1:-"dummy"}
		ali_start_container $context $what --detach $@
		if [ $detach != "--detach" ]; then
			exit 0
		fi
		sleep 2
	fi

	# setup the tmux layout if needed
	if [[ $TMUX && $USE_TMUX ]]; then
		ali_setup_tmux $context $what
	else
		echo "--- Connecting to container..."
		docker exec -it $context /bin/bash
	fi
}

ali_docker $@
