#!/bin/sh

ali_o2_pr_check() {
	local prnumber=$1
	local image=$2
	local what=$3
	docker volume create --name vc_alice_o2_src
	docker volume create --name vc_alice_alidist_src

	if [[ "$what" == "doit" ]]; then

		docker run --env PATH="$PATH":/home/laurent -it --rm \
			-v vc_alice_sw:$HOME/alice/sw:delegated \
			-v vc_alice_o2_src:$HOME/alice/O2:delegated \
			-v vc_alice_alidist_src:$HOME/alice/alidist:delegated \
			"$image" devtoolset.sh "pr-check.sh $prnumber O2"
	else
		docker run --env PATH="$PATH":/home/laurent -it --rm \
			-v vc_alice_sw:$HOME/alice/sw:delegated \
			-v vc_alice_o2_src:$HOME/alice/O2:delegated \
			-v vc_alice_alidist_src:$HOME/alice/alidist:delegated \
			"$image" bash
	fi

}

defaultimage=$(ali_default_image)

ali_o2_pr_check ${1:--1} ${2:-$defaultimage} ${3:-doit}
