#!/bin/bash

test -d $1 && exit 0

if [[ "$1" =~ ^[a-zA-Z0-9][a-zA-Z0-9_.-]+$ ]]; then
	docker volume create --name $1 > /dev/null
	exit 0
else
	echo "incorrect volume name $1"
	exit 1
fi

echo "non existing directory $1" && exit 2
