#!/bin/sh

ali_cvmfs() {

	# first argument (required) is the XXX::VVV string to be used
	# to issue the "alienv enter XXX::VVV" command at the
	# container startup
	#
	# remaining arguments are passed to the docker command itself
	# and can be used e.g. to bind mount more volumes
	#
	version=$1
	if [ $# -gt 0 ]; then
		shift
	fi

	docker_run_withX11 --rm --interactive --tty --privileged \
		-v $HOME/.globus:/root/.globus \
		-v $HOME/.rootrc:/root/.rootrc \
		-v /cvmfs:/cvmfs:cached \
		$@ aphecetche/centos7-ali-core $version
}

ali_cvmfs $@
