#!/bin/sh

ali_alo_pr_check() {
	docker volume create --name vc_alice_alo_src
	docker volume create --name vc_alice_alidist_src
	docker run --env PATH=$PATH:/home/laurent -it --rm \
		-v vc_alice_sw:$HOME/alice/sw \
		-v vc_alice_alo_src:$HOME/alice/alo \
		-v vc_alice_alidist_src:$HOME/alice/alidist \
		centos7-ali-core devtoolset.sh "pr-check.sh $1"
	# centos7-ali-core devtoolset.sh bash
}

ali_alo_pr_check $1
