#!/bin/sh

ali_setup_tmux() {

	# setup, if it does not exist yet, a window
	# in the current tmux session with the following layout :
	#
	# ---------------------------------------
	# |                  |                  |
	# |                  |                  |
	# |                  | build dir in     |
	# |                  | docker container |
	# |                  | (pane 2)         |
	# |                  |                  |
	# |  local dir       |-------------------
	# |  (pane 1)        |                  |
	# |                  | exec dir in      |
	# |                  | docker container |
	# |                  | (pane 3)         |
	# |                  |                  |
	# ---------------------------------------
	#

	local context=$1
	local what=$2
	local dir=$HOME/alice/$context
	local wname=$context
	local pane_localedit=1
	local pane_build=2
	local pane_exec=3

	tmux new-window -n $wname
	tmux split-window -h -t $wname
	tmux split-window -v -t $wname.2

	tmux send-keys -t $wname.$pane_exec "cd $dir; docker exec -it $wname /bin/bash" enter
	tmux send-keys -t $wname.$pane_build "cd $dir; docker exec -it $wname /bin/bash" enter
	tmux send-keys -t $wname.$pane_localedit "cd $dir/$what; export ALI_WHAT=$what; export
    ALI_CONTEXT=$context; " enter

	tmux send-keys -t $wname.$pane_build "cd /alice/sw/BUILD/$what-latest-$version/$what" enter

	for pane in 1 2 3; do
		tmux send-keys -t $wname.$pane "clear" enter
	done

	tmux send-keys -t $wname.$pane_build "pwd" enter
}
