#!/bin/sh

ali_alo_pr_check() {
	local prnumber=$1
	local image=$2
	docker volume create --name vc_alice_alo_src
	docker volume create --name vc_alice_alidist_src
	docker run --env PATH=$PATH:/home/laurent -it --rm \
		-v vc_alice_sw:$HOME/alice/sw \
		-v vc_alice_alo_src:$HOME/alice/alo \
		-v vc_alice_alidist_src:$HOME/alice/alidist \
		$image devtoolset.sh "pr-check.sh $prnumber"
}

defaultimage=$(ali_default_image)

ali_alo_pr_check ${1:--1} ${2:-$defaultimage}
