#!/bin/sh

volume_location=${1:-container}

case $volume_location in
  container)
  echo vc_alice_sw;;
  host)
  echo $HOME/alice/sw;;
  *)
  echo "don't know location $volume_location"
  exit 1
esac

exit 0

